/**
 * This file is auto-generated by type_generator.ts, DO NOT EDIT.
 */

export enum Type {
  Load = "mx/load",
  ConnectLoaded = "mx/connect/loaded",
  ConnectSelectedInstitution = "mx/connect/selectedInstitution",
  ConnectStepChange = "mx/connect/stepChange",
}

export const typeLookup: Record<string, Type> = {
  [Type.Load]: Type.Load,
  [Type.ConnectLoaded]: Type.ConnectLoaded,
  [Type.ConnectSelectedInstitution]: Type.ConnectSelectedInstitution,
  [Type.ConnectStepChange]: Type.ConnectStepChange,
}
