/**
 * This file is auto-generated by generate_types.ts, DO NOT EDIT.
 *
 * If you need to make changes to the code in this file, you can do so by
 * modifying definitions.yml.
 */
export enum Type {
  AccountCreated = "mx/account/created",
  ConnectConnectedPrimaryAction = "mx/connect/connected/primaryAction",
  ConnectCreateMemberError = "mx/connect/createMemberError",
  ConnectEnterCredentials = "mx/connect/enterCredentials",
  ConnectInstitutionSearch = "mx/connect/institutionSearch",
  ConnectLoaded = "mx/connect/loaded",
  ConnectMemberConnected = "mx/connect/memberConnected",
  ConnectMemberDeleted = "mx/connect/memberDeleted",
  ConnectMemberStatusUpdate = "mx/connect/memberStatusUpdate",
  ConnectOAuthError = "mx/connect/oauthError",
  ConnectOAuthRequested = "mx/connect/oauthRequested",
  ConnectSelectedInstitution = "mx/connect/selectedInstitution",
  ConnectStepChange = "mx/connect/stepChange",
  ConnectSubmitMFA = "mx/connect/submitMFA",
  ConnectUpdateCredentials = "mx/connect/updateCredentials",
  Load = "mx/load",
  Ping = "mx/ping",
}

export const typeLookup: Record<string, Type> = {
  [Type.AccountCreated]: Type.AccountCreated,
  [Type.ConnectConnectedPrimaryAction]: Type.ConnectConnectedPrimaryAction,
  [Type.ConnectCreateMemberError]: Type.ConnectCreateMemberError,
  [Type.ConnectEnterCredentials]: Type.ConnectEnterCredentials,
  [Type.ConnectInstitutionSearch]: Type.ConnectInstitutionSearch,
  [Type.ConnectLoaded]: Type.ConnectLoaded,
  [Type.ConnectMemberConnected]: Type.ConnectMemberConnected,
  [Type.ConnectMemberDeleted]: Type.ConnectMemberDeleted,
  [Type.ConnectMemberStatusUpdate]: Type.ConnectMemberStatusUpdate,
  [Type.ConnectOAuthError]: Type.ConnectOAuthError,
  [Type.ConnectOAuthRequested]: Type.ConnectOAuthRequested,
  [Type.ConnectSelectedInstitution]: Type.ConnectSelectedInstitution,
  [Type.ConnectStepChange]: Type.ConnectStepChange,
  [Type.ConnectSubmitMFA]: Type.ConnectSubmitMFA,
  [Type.ConnectUpdateCredentials]: Type.ConnectUpdateCredentials,
  [Type.Load]: Type.Load,
  [Type.Ping]: Type.Ping,
}
