/**
 * This file is auto-generated by generate_types.ts, DO NOT EDIT.
 *
 * If you need to make changes to the code in this file, you can do so by
 * modifying definitions.yml.
 */
export enum Type {
  AccountCreated = "mx/account/created",
  ConnectLoaded = "mx/connect/loaded",
  ConnectSelectedInstitution = "mx/connect/selectedInstitution",
  ConnectStepChange = "mx/connect/stepChange",
  Load = "mx/load",
  Ping = "mx/ping",
}

export const typeLookup: Record<string, Type> = {
  [Type.AccountCreated]: Type.AccountCreated,
  [Type.ConnectLoaded]: Type.ConnectLoaded,
  [Type.ConnectSelectedInstitution]: Type.ConnectSelectedInstitution,
  [Type.ConnectStepChange]: Type.ConnectStepChange,
  [Type.Load]: Type.Load,
  [Type.Ping]: Type.Ping,
}
